### ISSUE TITLE
additionalProperties is not False by default

### ISSUE THREAD

**Issue by Amedeo91** [Yelp/bravado#283] opened 2017-04-20 08:18 UTC
Is it possbile to have additionalProperties False by default without having to manually setted it?

Regards
Amedeo

**Comment by macisamuele** [comment] 2017-04-20 08:53
Forcing ``additionalProperties`` to ``False`` will make harder adding parameters (even optional) to specs so, personally, I think that it should be used carefully and so should not be enforced by default.
Additionally, "validation should check that the object is compliant with the schema provided" and so it should make sure that the properties defined by the json schema / swagger spec are present on the object and are respecting the constraints.

If you have different opinions could you share them with us? Any support will be appreciated.

**Comment by Amedeo91** [comment] 2017-04-20 09:57
Hi all,

for my application I need that the json contains only the parameters defined in the schema. To do that, I have to put additionalPorperties to false. I am not saying that should hard coded by default, but maybe there could be a configuration to change the behavior (like a global additionalProperties).

I think this functionality might be really useful especially if you want to validate response from the client and store the information using a NoSQL database (where you might store directly the json request).

Adding a optional parameter will require to add it in the swagger schema, which it is what you want to do when you want to provide documentation to the client.

Moreover I think that "validation should check that the object is compliant with the schema provided" does not mean that the object should contain any arbitrary field!! Or at least I should be able to have a choice!

Could you please reconsider your position? 

Thanks

Amedeo

**Comment by sjaensch** [comment] 2017-04-20 12:44
@Amedeo91 Swagger validation makes sure your object conforms to the spec. The spec says which fields need to be present and what the rules are for the values of those fields. By default it does not say that no additional fields should be present. This is by design and allows for forward compatibility: you can add new fields to a response and clients using an older version of the spec will not complain about the response containing those fields.

It sounds like you found a solution for your use case. I don't think it makes sense for us to allow you to override something you set in the spec by a config value, in essence not following the spec anymore. Is it really so hard to set it to `false`?

**Comment by Amedeo91** [comment] 2017-04-20 13:03
Hi all,

By default it does not say that no additional fields should be present. --> it does not even say that additional fields should be present

This is by design and allows for forward compatibility: you can add new fields to a response and clients using an older version of the spec will not complain about the response containing those fields. --> I do not think it is the right way to allow forward compatibility (especially in my case that I am developing a server). And I am not saying to remove it, but to allow people to choose how to do the validation.

It sounds like you found a solution for your use case. I don't think it makes sense for us to allow you to override something you set in the spec by a config value, in essence not following the spec anymore. Is it really so hard to set it to false? --> I have to recursive iterate on all the sub-documents aswell, and it is not really clean

I think that adding this feature could only improve the product (i.e. Cerberus json validator provides it with the ALLOW_UNKNOWN parameter). I am not using Cerberus, because Bravado is more flexible and allow me to create strong validation rule with less code.

Regards,
Amedeo

**Comment by laucia** [comment] 2017-04-20 13:51
@Amedeo91 https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-8.3.2
JsonSchema defines the additionalProperties as defaulting to `True`.

So the answer to your original question is No. For the schema to be valid under JsonSchema, we can't change the default. 

Bravado strives to respect the spec to the letter, because that's what people expect and what guaranties broader compatibility.

If you have special needs that bravado doesn't fit, maybe bravado is not the solution, or you need to build something on top of bravado to fit your needs perfectly.
Closing this

**Closed by laucia** 2017-04-20 13:51 UTC

**Comment by Amedeo91** [comment] 2017-04-20 14:40
If you have special needs that bravado doesn't fit, maybe bravado is not the solution, or you need to build something on top of bravado to fit your needs perfectly. --> it is exactly the contrary: Bravado meets of my need but for this aspect. Moreover, I DID NOT ASK TO CHANGE THE DEFAULT! 

I ask if you think it might be reasonable to extent the behavior since I believe that not having a global set-up to reject not allowed parameters is a shame.

Regards,
Amedeo
